default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost
  password:

development:
  <<: *default
  database: homepage_development

test:
  <<: *default
  database: homepage_test

production:
  <<: *default
  database: homepage_production
  username: root
  password: <%= ENV['HOMEPAGE_DATABASE_PASSWORD'] %>
